# Generated by Django 4.1.3 on 2022-11-10 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, max_length=150)),
                ('pPhoto', models.ImageField(blank=True, upload_to='profiles/pic/%Y/%m/%d/')),
                ('pBackground', models.ImageField(blank=True, upload_to='profiles/bg/%Y/%m/%d/')),
                ('rate', models.PositiveIntegerField(default=-1)),
                ('premium', models.BooleanField(default=False)),
                ('premium_exp', models.DateTimeField(auto_now_add=True)),
                ('map_link', models.URLField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('htmlFile', models.FileField(blank=True, upload_to='templates/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='templates/thumbnails/')),
                ('pTypes', models.ManyToManyField(blank=True, related_name='template_products', to='cafes.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafe_products', to='cafes.cafe')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='cafes.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_menus', to='cafes.cafe')),
                ('products', models.ManyToManyField(blank=True, related_name='menu_products', to='cafes.products')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_menus', to='cafes.templates')),
            ],
        ),
    ]
