# Generated by Django 4.1.3 on 2022-11-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='qr',
            field=models.ImageField(blank=True, upload_to='qrcode/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='map_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
