# Generated by Django 4.1.3 on 2022-12-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_cafe_pbackground_alter_cafe_pphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='pBackground',
            field=models.ImageField(blank=True, upload_to='profiles/bg/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='pPhoto',
            field=models.ImageField(blank=True, upload_to='profiles/pic/'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='htmlFile',
            field=models.FileField(blank=True, upload_to='templates/<django.db.models.fields.CharField>'),
        ),
    ]
