# Generated by Django 4.1.3 on 2022-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0008_alter_cafe_pphoto_alter_templates_htmlfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='htmlFile',
            field=models.FileField(blank=True, upload_to='templates/html'),
        ),
    ]
