# Generated by Django 4.1.3 on 2022-12-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0009_alter_templates_htmlfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('table', models.PositiveSmallIntegerField(blank=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_orders', to='cafes.cafe')),
                ('prods', models.ManyToManyField(blank=True, related_name='order_products', to='cafes.products')),
            ],
        ),
    ]
