# Generated by Django 4.1.3 on 2022-12-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0011_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.products')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='prods',
            field=models.ManyToManyField(blank=True, related_name='order_products', to='cafes.orderprod'),
        ),
    ]
