# Generated by Django 4.1.3 on 2022-12-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0014_alter_order_prods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderprod',
            name='number',
            field=models.PositiveIntegerField(blank=1),
        ),
    ]
