# Generated by Django 4.1.3 on 2022-12-22 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0017_alter_orderprod_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TableReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tNumber', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('endTime', models.TimeField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_tables_reserved', to='cafes.cafe')),
            ],
        ),
    ]
