# Generated by Django 4.1.3 on 2022-12-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0018_menu_isdefault_tablereserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereserve',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablereserve',
            name='reservedBy',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
