# Generated by Django 4.1.3 on 2023-01-18 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0019_tablereserve_cost_tablereserve_reservedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablereserve',
            name='reservedBy',
            field=models.CharField(default='مشتری', max_length=25),
        ),
        migrations.AlterField(
            model_name='tablereserve',
            name='tNumber',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='هزینه جاری', max_length=50)),
                ('price', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_costs', to='cafes.cafe')),
            ],
        ),
    ]
