# Generated by Django 4.1.3 on 2023-01-18 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0020_alter_order_table_alter_tablereserve_reservedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=models.DateTimeField(default=datetime.date(2023, 1, 18)),
        ),
    ]
