# Generated by Django 4.1.3 on 2023-01-28 11:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0023_alter_cost_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 11, 36, 42, 158609)),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='orders', max_length=15)),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_reports', to='cafes.cafe')),
            ],
        ),
    ]
