# Generated by Django 4.1.3 on 2023-01-28 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0024_alter_cost_date_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='dateFrom',
            field=models.DateField(default=datetime.datetime(2023, 1, 28, 12, 5, 40, 731482)),
        ),
        migrations.AddField(
            model_name='report',
            name='dateTo',
            field=models.DateField(default=datetime.datetime(2023, 1, 28, 12, 5, 40, 731482)),
        ),
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 12, 5, 40, 715908)),
        ),
    ]
