# Generated by Django 4.1.3 on 2023-09-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0031_products_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cafe',
            name='phoneNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='social',
            field=models.ManyToManyField(related_name='cafe', to='cafes.socialnetworkpage'),
        ),
    ]
