# Generated by Django 4.1.3 on 2023-09-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0032_socialnetworkpage_cafe_city_cafe_phonenum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='phoneNum',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
