# Generated by Django 4.1.3 on 2023-09-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0034_rename_name_socialnetworkpage_sn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='social',
            field=models.ManyToManyField(blank=True, related_name='cafe', to='cafes.socialnetworkpage'),
        ),
    ]
