# Generated by Django 4.1.3 on 2023-09-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0035_alter_cafe_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkpage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
