# Generated by Django 4.1.3 on 2024-04-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0036_alter_socialnetworkpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='slug',
            field=models.SlugField(max_length=20, null=True, unique=True),
        ),
    ]
