# Generated by Django 4.1.3 on 2024-04-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0037_cafe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='qr',
            field=models.ImageField(blank=True, upload_to='qrcode/%Y/%m/%d/'),
        ),
    ]
