# Generated by Django 4.1.3 on 2023-09-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_created_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='duration',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
